import { useState, useEffect, useRef, useCallback } from 'react'
import { useLang } from '../i18n.jsx'
import SectionHead from './SectionHead.jsx'
import Reveal from './Reveal.jsx'
import Photo from './Photo.jsx'

// Tiles are gallery-01 … gallery-12; each has a larger -full companion for the
// lightbox. Both are generated by scripts/optimize-images.py.
const COUNT = 12
const SHOTS = Array.from({ length: COUNT }, (_, i) => String(i + 1).padStart(2, '0'))

function Lightbox({ index, onClose, onStep }) {
  const { t } = useLang()
  const g = t.gallery
  const dialogRef = useRef(null)
  const closeRef = useRef(null)
  const lastFocused = useRef(null)

  useEffect(() => {
    lastFocused.current = document.activeElement
    document.body.style.overflow = 'hidden'
    const id = setTimeout(() => closeRef.current?.focus(), 0)
    return () => {
      clearTimeout(id)
      document.body.style.overflow = ''
      lastFocused.current?.focus?.()
    }
  }, [])

  useEffect(() => {
    const onKey = (e) => {
      if (e.key === 'Escape') onClose()
      else if (e.key === 'ArrowLeft') onStep(-1)
      else if (e.key === 'ArrowRight') onStep(1)
      else if (e.key === 'Tab') {
        // Keep focus inside the dialog.
        const focusable = dialogRef.current?.querySelectorAll('button')
        if (!focusable?.length) return
        const first = focusable[0]
        const last = focusable[focusable.length - 1]
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault()
          last.focus()
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault()
          first.focus()
        }
      }
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [onClose, onStep])

  const label = g.counter.replace('{n}', index + 1).replace('{total}', COUNT)

  return (
    <div className="lightbox" onClick={onClose}>
      <div
        className="lightbox__dialog"
        role="dialog"
        aria-modal="true"
        aria-label={label}
        ref={dialogRef}
        onClick={(e) => e.stopPropagation()}
      >
        <button ref={closeRef} type="button" className="lightbox__close" onClick={onClose}>
          <span aria-hidden="true">✕</span>
          <span className="sr-only">{g.close}</span>
        </button>

        <Photo
          name={`gallery-${SHOTS[index]}-full`}
          alt={g.alts[index]}
          width={1400}
          height={1867}
          className="lightbox__img"
        />

        <div className="lightbox__bar">
          <button type="button" className="lightbox__nav" onClick={() => onStep(-1)}>
            <span aria-hidden="true">←</span>
            <span className="sr-only">{g.prev}</span>
          </button>
          <p className="lightbox__counter">{label}</p>
          <button type="button" className="lightbox__nav" onClick={() => onStep(1)}>
            <span aria-hidden="true">→</span>
            <span className="sr-only">{g.next}</span>
          </button>
        </div>
      </div>
    </div>
  )
}

export default function Gallery() {
  const { t } = useLang()
  const g = t.gallery
  const [open, setOpen] = useState(null)

  const step = useCallback((d) => setOpen((i) => (i + d + COUNT) % COUNT), [])
  const close = useCallback(() => setOpen(null), [])

  return (
    <section id="gallery" className="section section--gallery">
      <div className="container">
        <SectionHead tag={g.tag} title={g.title} lead={g.lead} />

        <div className="gallery-grid">
          {SHOTS.map((n, i) => (
            <Reveal className="gallery-tile" key={n} delay={(i % 4) * 70}>
              <button
                type="button"
                className="gallery-tile__btn"
                onClick={() => setOpen(i)}
                aria-label={`${g.open} — ${g.alts[i]}`}
              >
                <Photo
                  name={`gallery-${n}`}
                  alt={g.alts[i]}
                  width={900}
                  height={1125}
                  className="gallery-tile__img"
                />
              </button>
            </Reveal>
          ))}
        </div>
      </div>

      {open !== null && <Lightbox index={open} onClose={close} onStep={step} />}
    </section>
  )
}
